### ISSUE TITLE
This is probably a bug

### ISSUE THREAD

**Issue by tmeshorer** [dkeras-project/dkeras#1]
config.N_CPUS_PER_SERVER = n_cpus_per_server
        config.N_CPUS_PER_WORKER = n_cpus_per_worker
        config.N_CPUS_PER_SERVER = n_gpus_per_worker <------

**Comment by stephenoffer** [comment]
Yes, thanks, that's a bug. The config part right now is simple because the next step will be automatic hardware configuration. Right now, it's set to Ray's defaults.
